config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  resources :posts, except: [:destroy] do
    member do
      post 'vote', to: 'posts#vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote', to: 'comments#vote'
      end
    end

  end

  resources :categories, only: [:show, :new, :create]

  resources :users, except: [:index, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  sluggable_column :name


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  
  belongs_to :user
  belongs_to :post

  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 4}
  validates :url, presence: true
  validates :description, presence: true

  sluggable_column :title



end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :password, presence: true, length: {minimum: 4}, on: :create
  validates :username, presence: true, uniqueness: true

  sluggable_column :username

  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator'
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post, polymorphic: true
  belongs_to :comment, polymorphic: true
  validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user, :require_login

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end

  def require_admin
    unless current_user.admin? and logged_in?
      access_denied
    end
  end


  def access_denied
    flash[:error] = "You cannot perform this action"
      redirect_to root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]


  def show
    @category = Category.find_by slug: params[:id]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "New category successfully created"
      redirect_to root_path
    else
      render :new
    end
  end


  private
    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login



  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comment successfully added"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(user_id: current_user.id, voteable_type: "Comment", voteable_id: @comment.id, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Thanks for voting."
        else
          flash[:error] = "You can only vote on a post once"
        end
        redirect_to :back
      end
      format.js do
        format.js
      end
    end

  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :vote]
before_action :require_login, except: [:show, :index]
before_action :require_admin_or_creator, only: [:edit, :update]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "Post successfully edited"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def require_admin_or_creator
    unless logged_in? and (current_user.id == @post.user_id or current_user.admin?)
      access_denied
    end
  end

  def vote
    @vote = Vote.create(user_id: current_user.id, voteable_type: "Post", voteable_id: @post.id, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Thanks for voting."
        else
          flash[:error] = "You can only vote on a post once"
        end
        redirect_to :back
      end
      format.js do
        format.js
      end
    end

  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_login, only: [:destroy]


  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Login successful. Welcome, #{user.username}"
      redirect_to root_path
    else
      flash[:error] = "Cannot find username or password. Please try again"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out"
      redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_same_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]


  def show
    end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :password, :time_zone))

    if @user.save
      flash[:notice] = "You successfully registered"
      redirect_to root_path
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(params.require(:user).permit(:username, :password, :time_zone))
      flash[:notice] = "Profile updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end


  private
    def require_same_user
    unless current_user != @user
      flash[:error] = "You can't perform this action"
      redirect_to root_path
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_fix(link)
    if link.start_with?("http")
      return link
    else return "http://#{link}"
    end
  end

  def date_fix(date)
    if logged_in? && !current_user.time_zone.blank?
      date = date.in_time_zone(current_user.time_zone)
    end
    date.strftime("%a %d %b %y, at %I:%M %p %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/form_error', form: @category %>

<%= form_for @category do |f| %>
<div class = 'well'>
    <p>
    <%= f.label :name, 'Category name' %>
    <%= f.text_field :name %>
    </p>
  <%= f.submit value: 'Submit category' , class: 'btn btn-primary' %>
</div>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new category' %>

<%= render 'form' %>

app/views/categories/show.html.erb
<% all_posts = link_to 'All Posts', posts_path %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
<%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comments.html.erb
<% show_post ||= false %>

<% object.comments.each do |comment| %>
<div class='row'>
  
  <div class='span1 well box'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(object, comment, vote: true), method: 'post', remote: true do %>
        <p class="vote"><i class="icon-arrow-up"></i></p>
      <% end %>
    <% end %>
    <span class="vote" id="comment_<%=comment.id%>_votes"><%=comment.total_votes %> votes</span>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(object, comment, vote: false), method: 'post', remote: true do %>
        <p class="vote"><i class="icon-arrow-down"></i></p>
      <% end %>
    <% end %>
  </div>

  <div class='span9 well box'>
    <p><em>"<%= comment.body%>"</em> 
      <% if show_post %>
        on <%= link_to comment.post.title, post_path(comment.post.id)%>
      <%end %>
    </p>
    <p class="quiet">Posted by <%= link_to comment.user.username, user_path(comment.user) %> on <%= date_fix(comment.created_at) %></p>
  </div> 

</div>
<% end %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes%> votes")
<% else %>
alert('You can only vote on a post once')
<%end%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <% if logged_in? %>
    <li>
    <div class="btn-group">
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      Categories
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
        <% if logged_in? and current_user.admin? %>
        <li class="divider"></li>
        <li><%= link_to 'New Category', new_category_path %></li>
        <% end %>
      </ul>
    </div>
  </li>
  <li>
    <div class="btn-group">
    <%= link_to 'New Post', new_post_path, class: "btn btn-success" %>
    </div>
  </li>
  <li>
    <div class="btn-group">
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      <%= current_user.username %>
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "View profile", user_path(current_user.slug) %></li>
        <li><%= link_to "Edit profile", edit_user_path(current_user.slug) %></li>
        <li><%= link_to "Log out", logout_path %></li>
      </ul>
    </div>
  </li>
  <% else %>
    <li>
    <div class="btn-group">
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      Categories
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
      </ul>
    </div>
  </li>
  <li>
    <div class="btn-group">
    <%= link_to 'Register', register_path, class: "btn btn-success" %>
    </div>
  </li>
  <li>
    <div class="btn-group">
    <%= link_to 'Log in', login_path, class: "btn btn-info" %>
    </div>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sarah's Postit App</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/form_error', form: @post %>



<%= form_for @post do |f| %>
<div class="well">
  <%= f.label :title %>
  <%= f.text_field :title %></br>
  <%= f.label :url, 'URL' %>
  <%= f.text_field :url %>
  <%= f.label :description %>
  <%= f.text_area :description,  rows: 7 %>
  </br>
  <%= f.label :category_ids, "Categories" %>
  <%= f.collection_check_boxes( :category_ids, Category.all, :id, :name, {:multiple => true}) do |b|
    b.label(class:"checkbox inline") {b.check_box(class: "checkbox inline") + b.text} 
  end
  %>

  </br></br>

  <%= f.submit 'Submit your post' , class: 'btn btn-primary' %>


  </div>
<% end %>

app/views/posts/_post.html.erb
<div class = "row">
  <div class ="span1 well box">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <p class="vote"><i class="icon-arrow-up"></i></p>
      <% end %>
    <% end %>
    <span class="vote" id="post_<%=post.slug%>_votes"><%= post.total_votes %> votes</span>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <p class="vote"><i class="icon-arrow-down"></i></p>
      <% end %>
    <% end %>

  </div>

  <div class = "span9 well box">
    <p><%= render post.categories %></p>
    <h4><%= link_to post.title, url_fix(post.url) %></h4>
    <p><%= post.description%></br></p>
    <p>
      <span class="quiet"><em> Created by <%= link_to post.user.username, user_path(post.user) %> on <%= date_fix(post.created_at) %></em></span></br>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </br>
    </p>
     <%= link_to("View post", post_path(post)) %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit a post" %>
<div>
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
<%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new post" %>
<div>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<p><%= render @post.categories %></p>
<% if logged_in? and (current_user.id == @post.user_id or current_user.admin?) %>
<p class='edit'><%= link_to 'Edit this post', edit_post_path(@post) %></p>
<% end %>
<%= render 'shared/content_title', title: @post.title %>



<p><%= @post.description %>
<hr>
</p>

<% if logged_in? %>
<p>Leave a comment
  <%= render 'shared/form_error', form: @comment %>
  <%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :body, rows: 5%>
  </br>
  <%= f.submit 'Submit comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>
</p>

<hr>
<h4>Comments</h4>
<%= render 'comments/comments', object: @post %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes%> votes")
<% else %>
alert('You can only vote on a post once')
<%end%>

app/views/shared/_content_title.html.erb
<p class = 'lead'>
  <%= title %>
<hr/>
</p>

app/views/shared/_form_error.html.erb
<% if form.errors.messages.any? %>
<div class= 'alert alert-error'>
  Please review the following errors:</br>
  <ul>
  <% form.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <%end %>
  </ul>
  </div>
<%end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<div class="well">
  <%= f.label :username %>
  <%= f.text_field :username %></br>
  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>
  <%= f.label :time_zone, 'Time Zone' %>
  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
  </br></br>
  <%= f.submit 'Submit' , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit profile" %>
<div>
<%= render 'shared/form_error', form: @user %>

<%= render 'form' %>
</div>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "Register" %>
<div>
<%= render 'shared/form_error', form: @user %>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class = "well box">
  <strong>Username:</strong> <%= @user.username %></br>
  <strong>Time zone:</strong> <%= @user.time_zone %>
</div>

<ul class="nav nav-tabs">
  <li><a href="#posts" data-toggle="tab">Posts (<%= @user.posts.size%>)</a></li>
  <li><a href="#comments" data-toggle="tab">Comments (<%= @user.comments.size%>)</a></li>
</ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="posts">
    <% if @user.posts.size > 0 %>
      <% @user.posts.each do |post| %>
      <%= render 'posts/post', post: post %>
      <% end %>
    <% else %>
    <p> You have not written any post yet. <%= link_to "Write a post now!", new_post_path %></p>
    <% end %>
  </div>
  <div class="tab-pane" id="comments">
    <% if @user.comments.size > 0 %>
      <%= render 'comments/comments', object: @user, show_post: true%>
    <% else %>
      <p> You have not written any comment yet.</p>
    <% end %>
  </div>
</div>
 